# Q.1

In [2]:
import numpy as np
arr = np.arange(2,50,3)
print("Output:\n",arr)

Output:
 [ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Q.2

In [12]:
import numpy as np
A = np.array([6,8,3,9,5])
B = np.array([2,11,7,4,17])
C = np.concatenate((A, B),axis=0)
C = np.sort(C,axis=0)
print("Output:\n",C)


Output:
 [ 2  3  4  5  6  7  8  9 11 17]


# Q.3

In [38]:
import numpy as np
a = np.array([[2,4,6],[8,10,12],[3,6,9]])
print('array:\n',a)
print('dimentions:',a.ndim,)
print('size:',a.size)


array:
 [[ 2  4  6]
 [ 8 10 12]
 [ 3  6  9]]
dimentions: 2
size: 9


# Q.4

In [86]:
import numpy as np
a = np.array([1,2,3,4])
b= np.expand_dims(a, axis= (1))
print(b)
print(np.newaxis is None)
print("\nReshape:\n",a.reshape(2,2))

[[1]
 [2]
 [3]
 [4]]
True

Reshape:
 [[1 2]
 [3 4]]


# Q.5

In [97]:
import numpy as np
a = np.array([1,2,3,5,6,7,8])
sqr = np.square(a)
print("square:\n",sqr)
print('Vertical :\n', np.vstack((sqr)))
print('Horizontal :', np.hstack((sqr)))

square:
 [ 1  4  9 25 36 49 64]
Vertical :
 [[ 1]
 [ 4]
 [ 9]
 [25]
 [36]
 [49]
 [64]]
Horizontal : [ 1  4  9 25 36 49 64]


# Q.6

In [105]:
list1 = [1, 2, 2, 5, 8, 4, 4, 8, 6, 7] 
l1 = [] 
  
count = 0
  
for item in list1: 
    if item not in l1: 
        count += 1
        l1.append(item) 
        
print("No of unique items are:", count) 


No of unique items are: 7
